fixed the app crash due to mapping of a null value
BKinya/Movies-App pull request #1
Opened 2022-11-27 18:34 UTC by agesa3

2022-11-29 23:13 UTC, BKinya requested changes

2022-11-29 23:13 UTC, BKinya commented on app/src/main/java/com/beatrice/moviesapp/data/model/Movie.kt
> +    val overview: String?= "",
This is great. Thank you for catching the crash. 

However, I'd prefer putting the null checks in the [this class](https://github.com/BKinya/Movies-App/blob/main/app/src/main/java/com/beatrice/moviesapp/data/network/model/Result.kt) and [this other one](https://github.com/BKinya/Movies-App/blob/main/app/src/main/java/com/beatrice/moviesapp/data/network/model/MovieNetworkResult.kt). 

Data is received as `MovieNetworkResult` then later and mapped to `Movie` domain model. I prefer to keep null values in the domain models at a minimal. I hope this makes sense. If not we can catch up on Whatsapp. If it does I'd appreciate you helping me implement the fix. Then I'll ,merge the changes. 

PS: I have updated the project. In case you experience merge conflicts make sure you have the latest changes from my main😀.

2022-11-29 23:19 UTC, agesa3 commented on app/src/main/java/com/beatrice/moviesapp/data/model/Movie.kt
> +    val overview: String?= "",
Will look at it then

2022-12-07 11:05 UTC, BKinya approved these changes

2022-12-07 11:06 UTC, merged