Test Database
BKinya/Movies-App pull request #6
Opened 2022-12-11 19:00 UTC by kanake10

This PR solves the following issues #2,  #3,  #5  inclusive of :

- Creating a `BaseDao` in the repo for inheritance in order to remove boilerplate code

2022-12-12 05:04 UTC, BKinya requested changes

2022-12-12 05:04 UTC, BKinya commented on app/build.gradle
> +    androidTestImplementation "com.google.truth:truth:1.0.1"
Instead of introducing a new library, `Google truth` library, let's use the existing libraries. `JUnit` will suffice for this project. 😃

2022-12-12 05:06 UTC, BKinya commented
@kanake10 Please check the comments. And feel free to ask if anything is not clear.

2022-12-12 06:26 UTC, agesa3 commented on app/src/main/java/com/beatrice/moviesapp/data/database/dao/BaseDao.kt
> +    suspend fun delete(items: List<T>)
When it comes to base classes I feel like they kind of introduce some complexity in the codebase.For no we want to have the project bing as simle and easy to understand for a beginner

2022-12-12 07:55 UTC, kanake10 commented on app/src/main/java/com/beatrice/moviesapp/data/database/dao/BaseDao.kt
> +    suspend fun delete(items: List<T>)
> @kanake10 For this PR, I do not favor base classes because of the complexity they introduce in a code base. In the spirit of keeping it simple, please remove the base classes.

Okay, working on it .

2022-12-12 07:56 UTC, kanake10 commented on app/build.gradle
> +    androidTestImplementation "com.google.truth:truth:1.0.1"
😂 ,making changes on this in a few

2022-12-12 08:07 UTC, kanake10 commented
> @kanake10 Please check the comments. And feel free to ask if anything is not clear.

The new changes pushed should solve the issues raised !

2022-12-12 15:11 UTC, BKinya approved these changes

2022-12-12 18:27 UTC, kanake10 commented
🤝

2022-12-12 18:33 UTC, agesa3 approved these changes

2022-12-12 18:34 UTC, agesa3 approved these changes
LGTM

2022-12-13 05:46 UTC, kanake10 commented
> LGTM

thanks @agesa3

2022-12-13 05:47 UTC, merged